### ISSUE TITLE
Crée un Readme Général sur L'organisation du projet

### ISSUE THREAD

**Issue by ClementBoesmier** [michelzahnd123/ClubMiniSumoNantes#2]
faire un README.md pour la desciption du projet sumo

TODO :

- [x] regarder comment son fait les Readme de grosse page Github
- [x] Description du projet
- [x] Organisation des Branchs
- [x] Organisation des Dossier
- [x] Organisation du GH Project
- [x] Comment compilé le projet
- [x] BONUS : comment contribuer au projet

**Comment by michelzahnd123** [comment]
Première version du README projet :
- Ambition
- Documentation
- Codage
- Vie du projet
Ajouter des liens, des images et des étiquettes pour faire comme "les grands"
