### ISSUE TITLE
Création d'un GitHub Wiki pour la documentation

### ISSUE THREAD

**Issue by ClementBoesmier** [michelzahnd123/ClubMiniSumoNantes#4]
Création de la document

TODO :
- [x] regarder des Wiki Exemple
- [x] crées une page d'accueil
- [x] création d'un pied de page
- [x] création d'une première page sur les ESC

**Comment by michelzahnd123** [comment]
Création d'une première page 
- partage des connaissances acquises dans le projet
- vie et gestion du projet
