### ISSUE TITLE
Création des Millestone

### ISSUE THREAD

**Issue by ClementBoesmier** [michelzahnd123/ClubMiniSumoNantes#5]
création des principale milestone du projet

TODO :

- [x] aller voir des projet existant
- [x] crée les principale milestone du projet

**Comment by michelzahnd123** [comment]
Création de 3 jalons pour le projet
- 19/12/2021 mise en place de la gestion de projet
- 10/2/2022 point d'hiver
- 14/4/2022 point du printemps, il reste 1 mois avant le tournoi

**Comment by michelzahnd123** [comment]
Milestone (jalonnement) fixé pour le projet  
- 16/12/2021  ... jeudi de cette semaine
- 10/2/2022  
- 14/4/2022  ... 1 mois avant le tournoi !
